"""Generate a self-contained static HTML specimen for Planetaire Mono Text.

The page loads the generated web fonts via the ``@font-face`` stylesheet produced
by ``build text`` and shows the weight ladder, legibility pairs, multilingual text,
a code sample, and a live dotted-zero (ss01) toggle. It is generated (not
hand-maintained) so it stays in sync with the fonts.
"""

from __future__ import annotations

from pathlib import Path

from planetaire.config import TEXT_FAMILY_NAME

_WEIGHTS: list[tuple[str, int]] = [
    ("Regular", 400),
    ("Medium", 500),
    ("Bold", 700),
    ("ExtraBold", 800),
]

_CODE_SAMPLE = """def planetaire(zero=0) -> bool:
    # Il1| O0o rn/m 5S 8B 2Z  <- legibility pairs
    items = {"a": [1, 2, 3], "b": (4, 5)}
    return all(x >= 0 for x in items["a"]) != zero"""


def _weight_rows() -> str:
    rows: list[str] = []
    for name, weight in _WEIGHTS:
        rows.append(
            f'<div class="row" style="font-weight:{weight}">'
            f'<span class="label">{name} {weight}</span>'
            f"<span>The quick brown fox jumps over the lazy dog 0123456789</span></div>"
        )
        rows.append(
            f'<div class="row" style="font-weight:{weight};font-style:italic">'
            f'<span class="label">{name} {weight} Italic</span>'
            f"<span>The quick brown fox jumps over the lazy dog 0123456789</span></div>"
        )
    return "\n".join(rows)


def generate_html_specimen(
    output_path: Path,
    *,
    css_href: str = "planetaire-mono-text.css",
    version: str | None = None,
) -> Path:
    """Write a self-contained ``specimen.html`` next to the Text web fonts.

    `css_href` is the relative path to the generated ``@font-face`` stylesheet;
    place the HTML in the same directory as the fonts + CSS for local preview.
    """
    if version is None:
        from planetaire.version import get_version, to_font_version

        version = to_font_version(get_version())

    family = TEXT_FAMILY_NAME
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{family} — Specimen</title>
<link rel="stylesheet" href="{css_href}">
<style>
  :root {{ --bg:#0d1117; --fg:#e6edf3; --dim:#7d8590; --accent:#58a6ff; }}
  * {{ box-sizing: border-box; }}
  body {{
    margin:0; padding:2.5rem clamp(1rem,4vw,4rem); background:var(--bg); color:var(--fg);
    font-family:'{family}', ui-monospace, monospace; line-height:1.5;
  }}
  header {{ border-bottom:1px solid #30363d; padding-bottom:1.5rem; margin-bottom:2rem; }}
  h1 {{ margin:0; font-weight:800; font-size:clamp(2rem,6vw,3.5rem); }}
  .sub {{ color:var(--dim); margin-top:.25rem; }}
  section {{ margin:2.5rem 0; }}
  h2 {{ font-size:.8rem; text-transform:uppercase; letter-spacing:.12em; color:var(--accent);
        font-weight:700; margin:0 0 1rem; }}
  .row {{ display:flex; gap:1.5rem; padding:.35rem 0; align-items:baseline; }}
  .label {{ color:var(--dim); flex:0 0 12rem; font-size:.8rem; }}
  .big {{ font-size:2rem; letter-spacing:.05em; }}
  pre {{ background:#161b22; border:1px solid #30363d; border-radius:8px; padding:1.25rem;
         overflow:auto; font-size:1rem; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(2.2rem,1fr));
           gap:.4rem; font-size:1.3rem; }}
  .grid span {{ text-align:center; padding:.3rem 0; background:#161b22; border-radius:4px; }}
  .toggle {{ display:flex; gap:.75rem; align-items:center; color:var(--dim); margin-bottom:1rem; }}
  .ss01 {{ font-feature-settings:'ss01' 1; }}
  footer {{ color:var(--dim); font-size:.8rem; border-top:1px solid #30363d;
            padding-top:1.5rem; margin-top:3rem; }}
</style>
</head>
<body>
<header>
  <h1>{family}</h1>
  <div class="sub">Version {version} — legible monospace for the web, built from B612 + Hack</div>
</header>

<section>
  <h2>Weights</h2>
  {_weight_rows()}
</section>

<section>
  <h2>Legibility</h2>
  <div class="row big"><span class="label">Confusables</span><span>Il1| O0o rn m 5S 8B 2Z</span></div>
  <div class="row big"><span class="label">Latin</span><span>ABCDEFGHIJKLM nopqrstuvwxyz</span></div>
  <div class="row big"><span class="label">Greek</span><span>ΑΒΓΔΕΖΗΘ αβγδεζηθ</span></div>
  <div class="row big"><span class="label">Cyrillic</span><span>АБВГДЕЖЗ абвгдежз</span></div>
  <div class="row big"><span class="label">Box drawing</span><span>┌─┬─┐ │ ├─┼─┤ └─┴─┘ ▓▒░█</span></div>
</section>

<section>
  <h2>Dotted zero (ss01)</h2>
  <label class="toggle"><input type="checkbox" id="ss01"> enable <code>ss01</code> (rectangle zero)</label>
  <div class="row big" id="zeros"><span class="label">0 vs O</span><span>0O 0O 0O — 1024 × 768 = 786432</span></div>
</section>

<section>
  <h2>Code</h2>
  <pre>{_CODE_SAMPLE}</pre>
</section>

<footer>Generated by <code>planetaire build html-specimen</code>.</footer>

<script>
  document.getElementById('ss01').addEventListener('change', function (e) {{
    document.getElementById('zeros').classList.toggle('ss01', e.target.checked);
  }});
</script>
</body>
</html>
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html)
    return output_path
